import '@styles/globals.css'

export const metadata = {
  title: "2Gopher",
  description: "Generated by create next app",
};

function Application({ Component, pageProps }) {
  return <Component {...pageProps} />
}

export default Application