import { Inter } from "next/font/google";
import "./globals.css";
import Nav from '@/app/components/Nav';
import Footer from '@/app/components/Footer';

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Imperium BCMA",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <Nav />
        {children}
        <Footer/>
      </body>
    </html>
  );
}
